version: '3.8'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    command: python app.py run -h 0.0.0.0
    ports:
      - 5000:5000
    env_file:
      - ./services/web/.env
    depends_on:
      - db
      - worker
    volumes:
      - ./download:/download
  worker:
    build:
      context: ./services/web
      dockerfile: Dockerfile.worker
    entrypoint: ["python", "worker.py"]
    env_file:
      - ./services/web/.env
    depends_on:
      - redis
    volumes:
      - ./download:/download
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev

volumes:
  postgres_data: